### ISSUE TITLE
Fatal error: Uncaught RuntimeException: Could not determine home directory. Set the PLATFORMSH_CLI_HOME environment variable.

### ISSUE THREAD

**Issue by alanmels** [platformsh/platformsh-cli#1150]
Followed installation steps on Ubuntu 20.04.4 LTS with PHP 8.1.9 and it's giving:

```
platform
Fatal error: Uncaught RuntimeException: Could not determine home directory. Set the PLATFORMSH_CLI_HOME environment variable. in phar:///usr/local/bin/platform/src/Service/Config.php:147
Stack trace:
#0 phar:///usr/local/bin/platform/src/Service/Config.php(179): Platformsh\Cli\Service\Config->getHomeDirectory()
#1 phar:///usr/local/bin/platform/src/Service/Config.php(261): Platformsh\Cli\Service\Config->getWritableUserDir()
#2 phar:///usr/local/bin/platform/src/Service/Config.php(32): Platformsh\Cli\Service\Config->getSessionIdFile()
#3 phar:///usr/local/bin/platform/src/Application.php(38): Platformsh\Cli\Service\Config->__construct()
#4 phar:///usr/local/bin/platform/bin/platform(33): Platformsh\Cli\Application->__construct()
#5 /usr/local/bin/platform(10): require('...')
#6 {main}
  thrown in phar:///usr/local/bin/platform/src/Service/Config.php on line 147
```

**Comment by pjcdawkins** [comment]
In the default terminal and default shell? This means the HOME variable is also not set

**Comment by pjcdawkins** [comment]
@alanmels did you manage to resolve this?

**Comment by alanmels** [comment]
@pjcdawkins I never did and migrated a website away using a different method.
