### ISSUE TITLE
`platform list` throws exception

### ISSUE THREAD

**Issue by amrishparmar** [platformsh/platformsh-cli#1190]
Attempting to run the `platform list` command results in an the following exception:

```
➜ platform list
Fatal error: Uncaught TypeError: Platformsh\Cli\Local\ApplicationFinder::getExplicitRoot(): Argument #1 ($appConfig) must be of type array, string given, called in phar:///home/amrish/.platformsh/bin/platform/src/Local/ApplicationFinder.php on line 91 and defined in phar:///home/amrish/.platformsh/bin/platform/src/Local/ApplicationFinder.php:119
Stack trace:
#0 phar:///home/amrish/.platformsh/bin/platform/src/Local/ApplicationFinder.php(91): Platformsh\Cli\Local\ApplicationFinder->getExplicitRoot()
#1 phar:///home/amrish/.platformsh/bin/platform/src/Local/ApplicationFinder.php(54): Platformsh\Cli\Local\ApplicationFinder->findGroupedApplications()
#2 phar:///home/amrish/.platformsh/bin/platform/src/Command/Environment/EnvironmentXdebugCommand.php(61): Platformsh\Cli\Local\ApplicationFinder->findApplications()
#3 phar:///home/amrish/.platformsh/bin/platform/src/Command/Environment/EnvironmentXdebugCommand.php(38): Platformsh\Cli\Command\Environment\EnvironmentXdebugCommand->isPhp()
#4 phar:///home/amrish/.platformsh/bin/platform/vendor/symfony/console/Descriptor/ApplicationDescription.php(108): Platformsh\Cli\Command\Environment\EnvironmentXdebugCommand->isHidden()
#5 phar:///home/amrish/.platformsh/bin/platform/vendor/symfony/console/Descriptor/ApplicationDescription.php(75): Symfony\Component\Console\Descriptor\ApplicationDescription->inspectApplication()
#6 phar:///home/amrish/.platformsh/bin/platform/src/Console/CustomTextDescriptor.php(102): Symfony\Component\Console\Descriptor\ApplicationDescription->getCommands()
#7 phar:///home/amrish/.platformsh/bin/platform/vendor/symfony/console/Descriptor/Descriptor.php(55): Platformsh\Cli\Console\CustomTextDescriptor->describeApplication()
#8 phar:///home/amrish/.platformsh/bin/platform/vendor/symfony/console/Helper/DescriptorHelper.php(67): Symfony\Component\Console\Descriptor\Descriptor->describe()
#9 phar:///home/amrish/.platformsh/bin/platform/src/Command/ListCommand.php(36): Symfony\Component\Console\Helper\DescriptorHelper->describe()
#10 phar:///home/amrish/.platformsh/bin/platform/vendor/symfony/console/Command/Command.php(255): Platformsh\Cli\Command\ListCommand->execute()
#11 phar:///home/amrish/.platformsh/bin/platform/vendor/symfony/console/Application.php(1010): Symfony\Component\Console\Command\Command->run()
#12 phar:///home/amrish/.platformsh/bin/platform/src/Application.php(331): Symfony\Component\Console\Application->doRunCommand()
#13 phar:///home/amrish/.platformsh/bin/platform/vendor/symfony/console/Application.php(255): Platformsh\Cli\Application->doRunCommand()
#14 phar:///home/amrish/.platformsh/bin/platform/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun()
#15 phar:///home/amrish/.platformsh/bin/platform/bin/platform(33): Symfony\Component\Console\Application->run()
#16 /home/amrish/.platformsh/bin/platform(10): require('...')
#17 {main}
  thrown in phar:///home/amrish/.platformsh/bin/platform/src/Local/ApplicationFinder.php on line 119
```

I installed it using the recommended install script

CLI:
```
➜  platform --version
Platform.sh CLI 3.86.0
```

OS:
```
Ubuntu 22.04.1 LTS
```

PHP:
```
➜ php --version
PHP 8.1.2-1ubuntu2.8 (cli) (built: Nov  2 2022 13:35:25) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.2, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.2-1ubuntu2.8, Copyright (c), by Zend Technologies
```

**Comment by pjcdawkins** [comment]
Hi @amrishparmar, it sounds like you have a `.platform/applications.yaml` which contains invalid config? It should be a list of objects e.g.:

```yaml
# .platform/applications.yaml
-
  name: app1
  type: php:8.1
-
  name: app2
  type: nodejs:18
```

**Comment by amrishparmar** [comment]
Thanks for looking into (and resolving this).

It does indeed seem that it was my `applications.yml` file that was the issue. Turns out a single space was the difference between it working and not.

Before (broken):
```yaml
 - !include poetry.app.yaml
```

After (working):
```yaml
- !include poetry.app.yaml
```
