### ISSUE TITLE
No output without iconv extension

### ISSUE THREAD

**Issue by spk** [platformsh/platformsh-cli#955]
Hi there,

Without this extension running the `platform workers` command gives
you an output like:

```
Workers on the project xxx (xxx), environment Master (master):
```

But without any output of the workers or error. Running it with verbose
mode give you more info:

```
    Fatal error: Uncaught Error: Call to undefined function Symfony\Polyfill\Mbstring\iconv() in phar:///root/.platformsh/bin/platform/vendor/symfony/polyfill-mbstring/Mbstring.php:713
    Stack trace:
     #0 phar:///root/.platformsh/bin/platform/vendor/symfony/polyfill-mbstring/bootstrap.php(102): Symfony\Polyfill\Mbstring\Mbstring::mb_strwidth('app--queue', 'ASCII')
     #1 phar:///root/.platformsh/bin/platform/vendor/symfony/console/Helper/Helper.php(54): mb_strwidth('app--queue', 'ASCII')
     #2 phar:///root/.platformsh/bin/platform/vendor/symfony/console/Helper/Helper.php(123): Symfony\Component\Console\Helper\Helper::strlen('app--queue')
     #3 phar:///root/.platformsh/bin/platform/src/Console/AdaptiveTable.php(353): Symfony\Component\Console\Helper\Helper::strlenWithoutDecoration(Object(Symfony\Component\Console\Formatter\OutputFormatter), 'app--queue')
     #4 phar:///root/.platformsh/bin/platform/src/Console/AdaptiveTable.php(267): Platformsh\Cli\Console\AdaptiveTable->getCellWidth('app--queue')
     #5 phar:///root/.platformsh/bin/platform/src/Co in phar:///root/.platformsh/bin/platform/vendor/symfony/polyfill-mbstring/Mbstring.php on line 713
```

env: LANG=C.UTF-8
Adding the `php-iconv` extension fixed the issue and I could see the workers list

I've noticed that this extension was checked before on the installer but then removed

Cheers,
Laurent

**Comment by pjcdawkins** [comment]
It looks like the `mbstring` extension would solve this too. The installer should be made to check for one of them.
